// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG6kYsXtRwMz2CSd3NiO8yqvuqBu9c9xw',
    appId: '1:679955835787:web:659fcfc81270787f331d8e',
    messagingSenderId: '679955835787',
    projectId: 'instruction-1b472',
    authDomain: 'instruction-1b472.firebaseapp.com',
    storageBucket: 'instruction-1b472.firebasestorage.app',
    measurementId: 'G-5DNYW85S0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevn-ABn3XaG8gigDgh_REmvpvA8bvlwg',
    appId: '1:679955835787:android:e5736068aedab84d331d8e',
    messagingSenderId: '679955835787',
    projectId: 'instruction-1b472',
    storageBucket: 'instruction-1b472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVAwI4Rbc9ibIzdYaQNHWkd-qSEWn8yQ',
    appId: '1:679955835787:ios:3af5c170a7cdd255331d8e',
    messagingSenderId: '679955835787',
    projectId: 'instruction-1b472',
    storageBucket: 'instruction-1b472.firebasestorage.app',
    iosBundleId: 'n',
  );

}